import { CommonModule } from '@angular/common'
import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core'

import { SharedModule } from '@shared/shared.module'
// import { ImpresoraModule } from '../APT/impresora/impresora.module'

import {
  // AlmacenComponent,
  // BodegaComponent,
  // BuqueComponent,
  // CatalogoEmbarqueComponent,
  // CausaCancelacionComponent,
  // CausaMovComponent,
  // CausaMovDisposicionComponent,
  // CausaReimpresionComponent,
  // CausaRetencionComponent,
  // CausaSuspensionComponent,
  // CausasLpdComponent,
  // CiaTransporteComponent,
  // CiudadesPaisEstadoComponent,
  // ClienteComponent,
  // ClienteDestinoComponent,
  // ClienteSolicitanteComponent,
  // ColadasValidasTcComponent,
  // ConductorComponent,
  // EdoGrupoInventarioComponent,
  // EdoOrdenComponent,
  EdoProgramaComponent,
  // EdoSolicitudComponent,
  // EmbarqueComponent,
  // EstadoPaisComponent,
  // EventoComponent,
  // FilaComponent,
  // FrenteExpedicionComponent,
  // FteDespComponent,
  // GrupoAlmacenComponent,
  // GrupoInventarioComponent,
  // GrupoInventarioDestinoComponent,
  // MarcasTrspComponent,
  // MediosTrspComponent,
  // MovimientoComponent,
  // NaveComponent,
  // OrdEntregaComponent,
  // OrdEntregaProgComponent,
  // PaisComponent,
  // PedidoVentaComponent,
  // PuertoComponent,
  // PuertoEmbarqueComponent,
  // StockCentroComponent,
  // SubEventoComponent,
  // TablaVirtualComponent,
  // TiposTrspComponent,
  // TranspCargaComponent,
  // TranspMovilComponent,
  // UbicExistenciaAlmComponent,
  // UbicacionComponent,
  // UsuarioComponent,
  // UsuariosXComandoComponent,
  // ZonaComponent
} from '.'

// import { CausaDisponibleComponent } from './causa-disponible/causa-disponible.component'
// import { PiezaComponent } from './pieza/pieza.component'
// import { ProductoAlternoComponent } from './producto-alterno/producto-alterno.component'

@NgModule({
  declarations: [
    EdoProgramaComponent
    // EdoOrdenComponent,
    // AlmacenComponent,
    // GrupoAlmacenComponent,
    // ClienteComponent,
    // BuqueComponent,
    // ConductorComponent,
    // PuertoComponent,
    // CiaTransporteComponent,
    // ClienteSolicitanteComponent,
    // ClienteDestinoComponent,
    // FrenteExpedicionComponent,
    // CausaCancelacionComponent,
    // OrdEntregaProgComponent,
    // OrdEntregaComponent,
    // FilaComponent,
    // NaveComponent,
    // FteDespComponent,
    // CausaMovComponent,
    // EventoComponent,
    // SubEventoComponent,
    // ZonaComponent,
    // CausaReimpresionComponent,
    // TranspMovilComponent,
    // TranspCargaComponent,
    // PaisComponent,
    // EmbarqueComponent,
    // PuertoEmbarqueComponent,
    // BodegaComponent,
    // EstadoPaisComponent,
    // CiudadesPaisEstadoComponent,
    // MarcasTrspComponent,
    // TiposTrspComponent,
    // UsuarioComponent,
    // CausaSuspensionComponent,
    // MediosTrspComponent,
    // MovimientoComponent,
    // CausaRetencionComponent,
    // EdoSolicitudComponent,
    // UsuariosXComandoComponent,
    // PedidoVentaComponent,
    // CatalogoEmbarqueComponent,
    // GrupoInventarioComponent,
    // GrupoInventarioDestinoComponent,
    // EdoGrupoInventarioComponent,
    // ProductoAlternoComponent,
    // PiezaComponent,
    // CausaDisponibleComponent,
    // ColadasValidasTcComponent,
    // UbicacionComponent,
    // CausaMovDisposicionComponent,
    // TablaVirtualComponent,
    // CausasLpdComponent,
    // StockCentroComponent,
    // UbicExistenciaAlmComponent
  ],
  imports: [
    CommonModule,
    SharedModule,
    // ImpresoraModule
  ],
  exports: [
    EdoProgramaComponent
    // EdoOrdenComponent,
    // AlmacenComponent,
    // GrupoAlmacenComponent,
    // ClienteComponent,
    // BuqueComponent,
    // ConductorComponent,
    // PuertoComponent,
    // CiaTransporteComponent,
    // ClienteSolicitanteComponent,
    // ClienteDestinoComponent,
    // FrenteExpedicionComponent,
    // CausaCancelacionComponent,
    // OrdEntregaProgComponent,
    // OrdEntregaComponent,
    // FilaComponent,
    // NaveComponent,
    // FteDespComponent,
    // CausaMovComponent,
    // EventoComponent,
    // SubEventoComponent,
    // ZonaComponent,
    // CausaReimpresionComponent,
    // TranspMovilComponent,
    // TranspCargaComponent,
    // PaisComponent,
    // EmbarqueComponent,
    // PuertoEmbarqueComponent,
    // ImpresoraModule,
    // BodegaComponent,
    // EstadoPaisComponent,
    // CiudadesPaisEstadoComponent,
    // MarcasTrspComponent,
    // TiposTrspComponent,
    // UsuarioComponent,
    // CausaSuspensionComponent,
    // MediosTrspComponent,
    // MovimientoComponent,
    // EdoSolicitudComponent,
    // UsuariosXComandoComponent,
    // PedidoVentaComponent,
    // CatalogoEmbarqueComponent,
    // CausaRetencionComponent,
    // GrupoInventarioComponent,
    // GrupoInventarioDestinoComponent,
    // EdoGrupoInventarioComponent,
    // ProductoAlternoComponent,
    // PiezaComponent,
    // CausaDisponibleComponent,
    // CausaMovDisposicionComponent,
    // ColadasValidasTcComponent,
    // UbicacionComponent,
    // TablaVirtualComponent,
    // CausasLpdComponent,
    // StockCentroComponent,
    // UbicExistenciaAlmComponent,
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class HelpsAptModule {}
